### PR TITLE
Cron module update

### PR DESCRIPTION
**Pull request by tom2tom**
When I tried to use this module, it crashed. I decided to fix that. I confess that I got a bit carried away, and tweaked quite a bit around your core process. Mostly to bring things up to 1.11 standard.

### CODE REVIEW

**Comment by totophe** [comment]
Hi tom2tom, I must confess that I don't follow this project anymore. Do you wish to take it over?

All the best,

JCC

**Comment by totophe** [comment]
Also I have updated some of your work, mostly the readme/doc, you might want to merge back :-)

**Comment by tom2tom** [comment]
On Tue, 21 Apr 2015 07:10:32 -0700
Jean-Christophe Cuvelier notifications@github.com wrote:

> Hi tom2tom, I must confess that I don't follow this project anymore. Do you wish to take it over?

Oops, I forgot all about this, until the last few days when I was updating my copy of the Cron module to also support CMSMS2+.

I'm happy to step up on this. Not that I expect there will be much activity.

How do we proceed?

Regards
Tom

**Comment by totophe** [comment]
Hi @tom2tom I just set you admin of the repository :-)

Do as you wish and best of luck ;-)

**Pull request merged**
